apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web2
  template: 
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: site
        image: cristianoalazaro/conversao-temperatura:v1
        ports:
        - containerPort: 8080